elasticsearchHosts: "http://elasticsearch.logging.svc.cluster.local:9200"

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: kibana.darshanm.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kibana.darshanm.space
      secretName: kibana-darshanm-space-tls
