replicaCount: 1

auth:
  enabled: true
  password: elasticpass

ingress:
  enabled: false

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

volumePermissions:
  enabled: true
