apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: "{{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}"
      ports:
        - containerPort: {{ .Values.mongodb.port }}
