apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sears-alert-rules
  namespace: monitoring
  labels:
    release: prometheus
    role: alert-rules
spec:
  groups:
    - name: node.rules
      rules:
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected on {{ $labels.instance }}"
            description: "CPU usage is above 80% for more than 2 minutes."

    - name: k8s.rules
      rules:
        - alert: PodCrashLooping
          expr: kube_pod_container_status_restarts_total > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod is crashing frequently"
            description: "Container has restarted more than 5 times in the last minute."

        - alert: AppDown
          expr: kube_deployment_status_replicas_available{deployment="backend"} < 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Backend service down"
            description: "No replicas of backend are running in the cluster."
