grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.darshanm.space
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - grafana.darshanm.space
        secretName: grafana-darshanm-space-tls

prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - prometheus.darshanm.space
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - prometheus.darshanm.space
        secretName: prometheus-darshanm-space-tls
  prometheusSpec:
    # This section tells Prometheus where to send its alerts (to Alertmanager)
    alerting:
      alertmanagers:
      - namespace: monitoring # IMPORTANT: Use the actual namespace where Alertmanager is deployed
        name: alertmanager-main # Default name for Alertmanager service in kube-prometheus-stack
        port: web
        scheme: http

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - alertmanager.darshanm.space
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - alertmanager.darshanm.space
        secretName: alertmanager-darshanm-space-tls
  alertmanagerSpec:
    config: |
      global:
        resolve_timeout: 5m

      route:
        receiver: 'email-receiver'
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      receivers:
        - name: 'email-receiver'
          email_configs:
            - to: 'poohn416@gmail.com' # REPLACE
              from: 'idarshankm@gmail.com' # REPLACE
              smarthost: 'smtp.gmail.com:587' # REPLACE
              auth_username: 'idarshankm@gmail.com' # REPLACE
              auth_password: 'xmua mdvh abfw iqdc' # REPLACE
              send_resolved: true
              require_tls: true