version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecomdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - ecommerce-net

  mongo:
    image: mongo:6
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net

  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  ecommerce-net:
    driver: bridge

volumes:
  - mongo-data:/data/db
  - redis-data:/data

volumes:
  mongo-data:
  redis-data:

