{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-sears-ingress # <--- HARDCODED NAME
  labels:
    app.kubernetes.io/name: frontend-app # <--- SIMPLIFIED/HARDCODED LABEL
    app.kubernetes.io/instance: frontend-release # <--- SIMPLIFIED/HARDCODED LABEL
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

  tls:
    - hosts:
        - {{ .Values.global.domainName | quote }}
      secretName: {{ .Values.global.domainName | replace "." "-" }}-tls-cert

  rules:
    - host: {{ .Values.global.domainName | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend # This is correctly referencing your frontend Service name
                port:
                  number: 80

          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend # This is correctly referencing your backend Service name
                port:
                  number: 80
{{- end }}