{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-sears-ingress
  labels:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/instance: frontend-release
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

  tls:
    - hosts:
        - {{ .Values.global.domainName | quote }}
      secretName: {{ .Values.global.domainName | replace "." "-" }}-tls-cert

  rules:
    - host: {{ .Values.global.domainName | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
{{- end }}
