{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
  spec:
    ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.global.domainName | quote }}
      secretName: {{ .Values.global.domainName | replace "." "-" }}-tls-cert

  rules:
    - host: {{ .Values.global.domainName | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
{{- end }}