pipeline {
  agent any

  environment {
    NAMESPACE = "sears"
  }

  stages {

    stage('Checkout Source Code') {
      steps {
        git url: 'https://github.com/Darshanm416/ecommerce-devops-project.git', branch: 'main'
      }
    }

    stage('Deploy Backend (includes MongoDB & Redis)') {
      steps {
        sh '''
          helm upgrade --install backend ./helm/backend \
            --namespace $NAMESPACE \
            --create-namespace
        '''
      }
    }

    stage('Deploy Frontend') {
      steps {
        sh '''
          helm upgrade --install frontend ./helm/frontend \
            --namespace $NAMESPACE
        '''
      }
    }

    stage('Deploy Nginx') {
      steps {
        sh '''
          helm upgrade --install nginx ./helm/nginx \
            --namespace $NAMESPACE
        '''
      }
    }

  }

  post {
    success {
      echo "✅ All components deployed to EKS in namespace '$NAMESPACE'"
    }
    failure {
      echo "❌ Deployment failed. Please check the logs and Helm templates."
    }
  }
}
