replicaCount: 1 # Default replica count

image:
  repository: "" # Placeholder, overridden by Terraform
  tag: ""        # Placeholder, overridden by Terraform
  pullPolicy: IfNotPresent

service:
  type: ClusterIP # Default service type
  port: 80 # Default frontend service port

ingress:
  enabled: true # Default, overridden by Terraform
  className: "" # Placeholder, overridden by Terraform (e.g., "alb")
  annotations: {} # Placeholder, overridden by Terraform
  hosts: []       # Placeholder, overridden by Terraform
  tls: []         # Placeholder, overridden by Terraform

resources: {} # Default, no specific resource requests/limits
